//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftMindSolution
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SoftmindWebservicesEntities : DbContext
    {
        public SoftmindWebservicesEntities()
            : base("name=SoftmindWebservicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sample> Samples { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
    
        public virtual ObjectResult<GetTodayMessage_Result> GetTodayMessage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTodayMessage_Result>("GetTodayMessage");
        }
    }
}
